# Generated by Django 5.1.6 on 2025-06-30 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=2000)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_mode', models.CharField(choices=[('OFFERT', 'Offert'), ('NEGOCIABLE', 'Négociable'), ('NON_NEGOCIABLE', 'Non négociable')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announce_images/')),
                ('specification', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='annonces.category')),
            ],
        ),
    ]
